### Problem2.py ###

####################
# Project Euler
#
# Even Fibonacci numbers
# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
####################

fibArray = [1, 2]
answer = 2
  
while fibArray[ len(fibArray) - 1 ] < 4000000:
  if fibArray[ len(fibArray) - 1 ] % 2:
    answer += fibArray[ len(fibArray) - 1 ]
    
  fibArray.append(fibArray[len(fibArray) - 1] + fibArray[ len(fibArray) - 2 ] )
  
print answer